// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKQNvhg-bqjMGRosGSnoxjTQ1kZ0TNl_8',
    appId: '1:782734170657:web:22caf2278dfc432e882160',
    messagingSenderId: '782734170657',
    projectId: 'redditclone-d16e9',
    authDomain: 'redditclone-d16e9.firebaseapp.com',
    storageBucket: 'redditclone-d16e9.appspot.com',
    measurementId: 'G-12YVWJTY25',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoEBwbOfH0kbCShu2INK2KemjgSI517zU',
    appId: '1:782734170657:android:0179c05fe382dc6d882160',
    messagingSenderId: '782734170657',
    projectId: 'redditclone-d16e9',
    storageBucket: 'redditclone-d16e9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlHM0CQ-uKRGHmb29rMobZldCvypliGeo',
    appId: '1:782734170657:ios:b2b83f69382b8ed7882160',
    messagingSenderId: '782734170657',
    projectId: 'redditclone-d16e9',
    storageBucket: 'redditclone-d16e9.appspot.com',
    iosClientId: '782734170657-df22rkviom224co3rqsvmev6o9jjfqa4.apps.googleusercontent.com',
    iosBundleId: 'com.example.redditClone',
  );
}
